### ISSUE TITLE
spec: Consensus is called under wrong conditions

### ISSUE THREAD

**Issue by martin-hutle** [circlefin/malachite#670]
In handleProposal in driver.qnt, consensus is called with ProposalAndPolkaAndValidCInput while being in the prevote step:
https://github.com/informalsystems/malachite/blob/1d194fa25adab04ad1294080265d230122acffa5/specs/consensus/quint/driver.qnt#L218-L222
This results in an error in consensus.qnt:
https://github.com/informalsystems/malachite/blob/1d194fa25adab04ad1294080265d230122acffa5/specs/consensus/quint/consensus.qnt#L224-L239

**Comment by cason** [comment]
> In handleProposal in driver.qnt, consensus is called with ProposalAndPolkaAndValidCInput while being in the prevote step:

I assume you mean `propose` step here.

**Comment by cason** [comment]
In any case, if this event is observed before the `prevote` step it should be "buffered" to be processed once the `propose` step is concluded.

Actually, the only possibility (I am considering the [pseudo code](https://github.com/informalsystems/malachite/blob/main/specs/consensus/pseudo-code.md)) of having this event as the next to process while in the `propose` step, is that the `Proposal` message contains a valid round `vr > -1` and the corresponding proof-of-lock of round `vr` is not available. In this case, line 28 is not triggered until: (i) a `POL(vr, v)` is observed or (ii) `timeout_propose` expires. In both cases, we move to the `prevote` step and should immediately process the pending `ProposalAndPolkaAndValidCInput` event.
